### ISSUE TITLE
V4V and Boostagram supporting apps link

### ISSUE THREAD

**Issue by dwvisser** [dwvisser/v4v_exchange#2]
podcastindex.org/apps

**Comment by dwvisser** [comment]
This is present as far as podcastindex.org supports. I would like to have a link that shows filtering on Value-supporting podcatchers. There is an issue tracker for them to provide this: https://github.com/Podcastindex-org/web-ui/issues/139

**Comment by dellagustin** [comment]
There you go: 
https://podcastindex.org/apps?appTypes=podcast+player&elements=Value
or
https://podcastindex.org/apps?appTypes=podcast+player&elements=Sat+Streaming

**Comment by dwvisser** [comment]
Fixed in commit 7814c75. Thanks @dellagustin!
