### ISSUE TITLE
[feat] Docker container

### ISSUE THREAD

**Issue by nwithan8** [dwvisser/v4v_exchange#4]
Could you explore making a Docker container that just serves the web UI?

**Comment by dwvisser** [comment]
I found this to use as the base image: https://github.com/lipanski/docker-static-website

Now, I'd like to do this properly, and also set up a GitHub action that automatically deploys to Docker Hub and/or GitHub Container Registry whenever I push a change to *main*.

**Comment by dwvisser** [comment]
This shows how to publish to container registries whenever a release is created, which makes more sense, actually. I can create releases labelled by date, with corresponding tags on the built images.

https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images

**Comment by nwithan8** [comment]
A sample GitHub Action I use to auto-release one of my own Docker projects whenever I cut a release on GitHub: https://github.com/nwithan8/tauticord/blob/master/.github/workflows/docker.yml

**Comment by dwvisser** [comment]
This site is changed so infrequently, I'm not going to worry about automating for now. See https://hub.docker.com/repository/docker/dalevisser/v4v-exchange/ for the image I created. If ARM is important, I can re-open this issue and implement the automation.
